import { ArrowRight, Cpu, Film, Layers3, PenTool, Smartphone, WalletCards } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { Badge, Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { templates } from '@/lib/templates';

export function LandingPage() {
  const badges = ['No cloud GPU', 'No diffusion AI', 'SVG/vector assets', 'Local-first projects', 'Remotion + FFmpeg ready', 'APK-friendly architecture'];
  return <AppShell><main className="overflow-hidden">
    <section className="relative mx-auto grid max-w-7xl gap-10 px-4 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-24">
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_20%_10%,rgba(37,99,235,.16),transparent_30%),radial-gradient(circle_at_80%_20%,rgba(249,115,22,.14),transparent_28%)]" />
      <div><Badge>Canva + Whiteboard Animation + Automated Video Builder</Badge><h1 className="mt-6 max-w-4xl text-5xl font-black tracking-tight md:text-7xl">Create whiteboard explainer videos from scripts using local vectors.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">SketchFlow AI turns scripts into scene plans, matched doodles, marker-style animations, timelines, subtitles, narration sync placeholders, and Remotion compositions without expensive remote generation.</p><div className="mt-8 flex flex-wrap gap-3"><Button href="/editor">Open editor <ArrowRight className="h-4 w-4" /></Button><Button href="/templates" variant="secondary">Browse templates</Button></div><div className="mt-8 flex flex-wrap gap-2">{badges.map((badge) => <Badge key={badge}>{badge}</Badge>)}</div></div>
      <div className="relative"><div className="sketch-grid aspect-video rounded-[2.5rem] border bg-white p-8 shadow-sketch dark:border-slate-800 dark:bg-slate-900"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.25em] text-blue-600">Scene 01</p><h3 className="text-3xl font-black">Elephant dances happily</h3></div><PenTool className="h-10 w-10 animate-float text-blue-600" /></div><div className="grid grid-cols-3 gap-4"><Card className="sketch-border col-span-2 h-44 text-slate-900 dark:text-white"><p className="font-bold">Auto-matched assets</p><div className="mt-6 text-6xl">🐘 ✨ 📈</div></Card><Card className="h-44"><p className="text-sm font-bold">Timeline</p><div className="mt-5 space-y-2"><span className="block h-5 rounded bg-blue-500" /><span className="block h-5 rounded bg-orange-400" /><span className="block h-5 rounded bg-emerald-500" /></div></Card></div></div></div>
    </section>
    <section className="mx-auto grid max-w-7xl gap-4 px-4 pb-16 md:grid-cols-3">{[{ icon: Layers3, title: 'Template-driven', text: `${templates.length} typed whiteboard styles with reusable backgrounds, typography, defaults, and animation presets.` }, { icon: Cpu, title: 'Local engines', text: 'Pure TypeScript script parsing, asset ranking, placement, timelines, and storage abstractions.' }, { icon: Film, title: 'Real render path', text: 'Remotion composition code mirrors editor data and prepares future FFmpeg MP4 rendering.' }, { icon: WalletCards, title: 'Low-cost deployment', text: 'No GPU queue, no image model billing, no secret API keys, no remote AI dependency.' }, { icon: Smartphone, title: 'Vertical-ready', text: '16:9 YouTube and 9:16 Shorts templates, preview, timeline, and export settings.' }, { icon: PenTool, title: 'Hand-drawn feel', text: 'SVG stroke reveal, marker overlays, sketch motion, Framer Motion, and GSAP-contained adapters.' }].map((item) => <Card key={item.title}><item.icon className="h-8 w-8 text-blue-600" /><h3 className="mt-4 text-xl font-black">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{item.text}</p></Card>)}</section>
  </main></AppShell>;
}
